### ISSUE TITLE
Bug: newlines not working

### ISSUE THREAD

**Issue by bluecanarybe** [mholt/curl-to-go#36]
Hi,

Your latest update has a bug where new lines (using \) are not working. Even some of your examples don't work anymore.

**Comment by bakert** [comment]
This is a funny one.

The issue is caused by https://github.com/mholt/curl-to-go/pull/35 and it breaks Example 2 and most other multiline commands.

#35 attempts to add a commented-out copy of the original command in the header. However it naïvely assumes that prepending the input with `//` will be enough to achieve that.

```
var originalCmd = `// Original command: ${curl}`;
```

For a multiline command that gives us something like:

```
// Original command: curl \
--request POST \
http://localhost
```

which is not what the caller of `curlToGo` expects. It expects to be able to parse the output as Go code.

**Comment by BlueCanary-DM** [comment]
I've found a workaround myself when I needed it, but thanks for the fix anyway. Appreciate your project!

**Comment by bluecanarybe** [comment]
I've found a workaround myself when I needed it, but thanks for the fix anyway. Appreciate your project!
